### ISSUE TITLE
MainActivityの作成

### ISSUE THREAD

**Issue by Miyuseru** [Miyuseru/TimeSaber#1]
## 概要
・MainActivityの作成
・カレンダーを作る（2週間）
　リニアレイアウト組み合わせる
　現在の日付を取得して直近（月〜日　×２）2週間を表示→テキストに表示させる(https://itneko.com/kotlin-datetime/)
　横スワイプで行ったり来たりできる→左右ボタンで実装も可能

・プラスボタン→CreateActivityに飛べるように

**Comment by tommy1038** [comment]
>横スワイプでいったりきたりできる．

参考のアプリを読んだ感じ，ViewPagerとPageAdapterを使って実装してる感じ．
Fragmentが出てくるので，まずは基本的なコア機能の実装に力を注ぐべき．

## 参考サイト
ViewPagerとPagerAdapterでスワイプビューを作ってみる - Qiita https://qiita.com/shira-jun/items/1c40b087b38a370c6d18

**Comment by tommy1038** [comment]
* カレンダー上で，タスクが入ると横に幅を取ってくれる仕様について

参考アプリを読んだ感じ，'event background rectangle' でタスクが入っていたら，期限を取得して短形を描いている感じ！

## 参考
* 矩形を描く - Androidプログラマへの道 ～ Moonlight 明日香 ～ https://seesaawiki.jp/w/moonlight_aska/d/%B6%EB%B7%C1%A4%F2%C9%C1%A4%AF

* https://github.com/SimpleMobileTools/Simple-Calendar/blob/master/app/src/main/kotlin/com/simplemobiletools/calendar/pro/views/MonthView.kt#L226
